name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven Verify
        run: |
          ./mvnw --batch-mode --no-transfer-progress -B package

      - name: Docker compose
        run: |
          docker compose up --build -d
          sleep 30
          curl -X POST http://localhost:8080/api/v1/messages \
          -H 'Content-Type: application/json' \
          -d '{"message" : "hello world"}'
          docker-compose stop